package com.crashlab.analyzer.domain

/**
 * Core domain models.
 *
 * IMPORTANT DESIGN NOTE:
 * Nothing in this package predicts future rounds. Every computation here is a
 * *descriptive* statistic over rounds that already happened. Crash/Aviator
 * outcomes are generated by provably-fair RNG; past rounds are independent of
 * future rounds. The app surfaces this repeatedly in the UI.
 */

/** A single historical round result. */
data class Round(
    val id: Long = 0L,
    val multiplier: Double,
    val timestamp: Long,
    val platform: String = "manual"
)

/** Supported data sources (user-entered / imported, never scraped live). */
enum class Platform(val key: String, val label: String) {
    MANUAL("manual", "Manual"),
    ONEXBET("1xbet", "1xBet"),
    ROOBET("roobet", "Roobet"),
    STAKE("stake", "Stake"),
    OTHER("other", "Other");

    companion object {
        fun from(key: String): Platform = entries.firstOrNull { it.key == key } ?: OTHER
    }
}

/** Traffic-light volatility band. 🟢 🟡 🔴 */
enum class RiskBand { GREEN, AMBER, RED }

/**
 * Descriptive statistics over a window of past rounds.
 * All fields are backward-looking.
 */
data class StatsSummary(
    val count: Int,
    val mean: Double,
    val median: Double,
    val geometricMean: Double,
    val stdDev: Double,
    val min: Double,
    val max: Double,
    val bustRate: Double,          // share of rounds < 2.00x
    val instantBustRate: Double,   // share of rounds < 1.20x
    val highRate: Double,          // share of rounds >= 10.00x
    val longestSubTwoStreak: Int,
    val currentSubTwoStreak: Int,
    val impliedHouseEdge: Double,  // 1 - (empirical EV of a 1.00x hold)
    val quantiles: Map<Int, Double>
) {
    companion object {
        val EMPTY = StatsSummary(
            0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0, 0, 0.0, emptyMap()
        )
    }
}

/** Empirical survival point: P(round >= target) measured on history. */
data class SurvivalPoint(
    val target: Double,
    val empiricalProbability: Double,
    val theoreticalProbability: Double, // 0.99 / target, classic crash model
    val sampleSize: Int
) {
    /** Wilson score 95% interval half-width — honesty about sample noise. */
    val marginOfError: Double
        get() {
            if (sampleSize <= 0) return 1.0
            val z = 1.96
            val n = sampleSize.toDouble()
            val p = empiricalProbability
            return z * kotlin.math.sqrt((p * (1 - p) + z * z / (4 * n)) / n) / (1 + z * z / n)
        }
}

/** Volatility / risk read-out for the current window. */
data class RiskAssessment(
    val band: RiskBand,
    val score: Int,                 // 0..100, higher = choppier recent history
    val headline: String,
    val detail: String,
    val factors: List<RiskFactor>
)

data class RiskFactor(
    val label: String,
    val value: String,
    val contribution: Int,
    val band: RiskBand
)

/** A histogram bucket for charting. */
data class Bucket(
    val label: String,
    val lower: Double,
    val upper: Double,
    val count: Int,
    val share: Double
)

// ---------- Strategy simulation ----------

enum class StrategyType { FLAT, MARTINGALE, DALEMBERT, FIBONACCI, PERCENT_BANKROLL }

data class StrategyConfig(
    val type: StrategyType = StrategyType.FLAT,
    val startingBankroll: Double = 1000.0,
    val baseStake: Double = 10.0,
    val cashOutAt: Double = 2.0,
    val maxRounds: Int = 500,
    val stopLossPct: Double = 50.0,   // stop when bankroll drops this % below start
    val takeProfitPct: Double = 50.0, // stop when bankroll rises this % above start
    val maxStakeMultiple: Double = 64.0
)

data class EquityPoint(val round: Int, val bankroll: Double, val stake: Double, val won: Boolean)

data class SimulationResult(
    val config: StrategyConfig,
    val finalBankroll: Double,
    val peakBankroll: Double,
    val troughBankroll: Double,
    val maxDrawdownPct: Double,
    val roundsPlayed: Int,
    val wins: Int,
    val losses: Int,
    val totalStaked: Double,
    val ruin: Boolean,
    val hitStopLoss: Boolean,
    val hitTakeProfit: Boolean,
    val longestLosingStreak: Int,
    val equity: List<EquityPoint>
) {
    val netProfit: Double get() = finalBankroll - config.startingBankroll
    val roiPct: Double get() = if (config.startingBankroll == 0.0) 0.0
        else netProfit / config.startingBankroll * 100.0
    val winRate: Double get() = if (roundsPlayed == 0) 0.0 else wins.toDouble() / roundsPlayed
}

/** Aggregated Monte-Carlo style outcome across many replays. */
data class MonteCarloResult(
    val runs: Int,
    val medianFinal: Double,
    val meanFinal: Double,
    val p05: Double,
    val p95: Double,
    val ruinRate: Double,
    val profitRate: Double,
    val worstDrawdownPct: Double
)
